# Generated by Django 5.0 on 2026-09-13 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institusi', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('started_year', models.PositiveIntegerField()),
                ('ended_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
