# Generated by Django 5.0 on 2026-09-14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_education_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("certificate_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
    ]
