# Generated by Django 5.0 on 2026-10-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_education_starred_by_experience_starred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='starred_by',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='starred_by',
        ),
    ]
